<?php
declare(strict_types=1);
/**
 * ChatPopup.AI — i18n helper
 * Supported: en · id · es · fr · pt · ja
 */

function get_lang(): string {
    $allowed = ['en','id','es','fr','pt','ja'];
    if (!empty($_GET['lang'])) {
        $q = strtolower(trim((string)$_GET['lang']));
        if (in_array($q, $allowed, true)) {
            setcookie('cp_lang', $q, time() + 60*60*24*365, '/', '', false, false);
            return $q;
        }
    }
    if (!empty($_COOKIE['cp_lang'])) {
        $c = strtolower(trim((string)$_COOKIE['cp_lang']));
        if (in_array($c, $allowed, true)) return $c;
    }
    return 'en';
}

function lang_switch_url(string $lang): string {
    $allowed = ['en','id','es','fr','pt','ja'];
    $lang = strtolower(trim($lang));
    if (!in_array($lang, $allowed, true)) {
        $lang = 'en';
    }

    $uri = (string) ($_SERVER['REQUEST_URI'] ?? '/');
    $path = (string) (parse_url($uri, PHP_URL_PATH) ?: '/');
    $query = [];
    parse_str((string) (parse_url($uri, PHP_URL_QUERY) ?? ''), $query);
    $query['lang'] = $lang;

    return $path . '?' . http_build_query($query);
}

function app_url(string $path = '/', array $params = []): string {
    $lang = get_lang();
    if ($lang !== '') {
        $params['lang'] = $lang;
    }

    $query = http_build_query($params);
    return $query !== '' ? $path . '?' . $query : $path;
}

function lang_meta(): array {
    return [
        'en' => ['flag' => '🇺🇸', 'label' => 'English'],
        'id' => ['flag' => '🇮🇩', 'label' => 'Indonesia'],
        'es' => ['flag' => '🇪🇸', 'label' => 'Español'],
        'fr' => ['flag' => '🇫🇷', 'label' => 'Français'],
        'pt' => ['flag' => '🇧🇷', 'label' => 'Português'],
        'ja' => ['flag' => '🇯🇵', 'label' => '日本語'],
    ];
}

function lang_strings(string $lang): array {
    $all = [

    /* ══ ENGLISH ══════════════════════════════════════════════════ */
    'en' => [
        'html_lang'      => 'en',
        'dir'            => 'ltr',
        'page_title'     => 'ChatPopup.AI — AI Chat Widget for Any Website',
        'page_desc'      => 'Add an AI chat widget to your website in 5 minutes. Multi-provider (OpenAI, Gemini, DeepSeek, OpenRouter), custom branding, conversation memory.',
        /* nav */
        'nav_features'   => 'Features',
        'nav_how'        => 'How It Works',
        'nav_providers'  => 'Providers',
        'nav_login'      => 'Log In',
        'nav_register'   => 'Start Free',
        /* hero */
        'hero_eyebrow'   => 'Free Trial · No Credit Card',
        'hero_h1_a'      => 'AI Assistant',
        'hero_h1_b'      => 'for your website',
        'typewords'      => 'in 5 minutes|without coding|for anyone',
        'hero_p'         => 'One line of code. All AI providers supported. Custom colors, persona & bot instructions — managed from the dashboard, no database needed.',
        'cta_start'      => 'Start Free',
        'cta_login'      => 'Already have an account',
        'trust_1'        => '5-min setup',
        'trust_2'        => 'No coding',
        'trust_3'        => 'Custom brand',
        'float_1'        => 'Instant reply',
        'float_2'        => 'Secure & Encrypted',
        'mock_bot'       => 'Hi! How can I help you today?',
        'mock_user'      => 'Tell me about this product',
        /* ticker */
        'tick_items'     => 'OpenAI GPT-4o|Google Gemini|DeepSeek Chat|OpenRouter|AES-256 Encrypted|5 min setup|No coding needed|6 languages|Chat memory|Telegram alerts',
        /* stats */
        'stat_1_v'       => '5',
        'stat_1_suf'     => ' min',
        'stat_1_lbl'     => 'Average setup time',
        'stat_2_v'       => '4',
        'stat_2_suf'     => '',
        'stat_2_lbl'     => 'AI providers supported',
        'stat_3_v'       => '1',
        'stat_3_suf'     => ' line',
        'stat_3_lbl'     => 'To embed the widget',
        'stat_4_v'       => '99.9',
        'stat_4_suf'     => '%',
        'stat_4_lbl'     => 'Uptime SLA',
        /* features */
        'feat_tag'       => 'Key Features',
        'feat_h2'        => "Everything you need,\nready from day one",
        'feat_sub'       => 'From setup to context-aware AI conversations — all self-managed from the dashboard.',
        'feat_1_h'       => 'Live in 5 Minutes',
        'feat_1_p'       => 'Copy one script tag from the dashboard, paste to your website. Widget appears on every page instantly.',
        'feat_2_h'       => 'Multi-Provider AI',
        'feat_2_p'       => 'OpenRouter, OpenAI, Gemini, DeepSeek. Switch provider anytime from a dropdown — no code change.',
        'feat_3_h'       => 'Fully Customizable',
        'feat_3_p'       => 'Primary color, bot name, welcome message, system prompt — all following your brand.',
        'feat_4_h'       => 'Conversation Memory',
        'feat_4_p'       => 'AI remembers context within a session. Visitors never need to repeat themselves.',
        'feat_5_h'       => 'Telegram Alerts',
        'feat_5_p'       => 'Get notified via Telegram every time a new message arrives — no dashboard needed.',
        'feat_6_h'       => 'Secure & Isolated',
        'feat_6_p'       => 'Shadow DOM protects widget CSS. AI API keys are AES-256-GCM encrypted in the database.',
        /* how */
        'how_tag'        => 'How It Works',
        'how_h2'         => 'Three steps. AI widget live.',
        'how_sub'        => 'No technical expertise needed. If you can copy-paste, you can use this.',
        'step_1_h'       => 'Sign Up & Configure',
        'step_1_p'       => 'Choose AI provider, enter API key, write a system prompt for your business.',
        'step_2_h'       => 'Copy Embed Code',
        'step_2_p'       => 'Dashboard auto-generates a unique script tag. One click, copied to clipboard.',
        'step_3_h'       => 'Paste to Website',
        'step_3_p'       => 'Paste before &lt;/body&gt; in WordPress, Webflow, or any landing page.',
        /* providers */
        'prov_tag'       => 'AI Providers',
        'prov_h2'        => 'Pick the best AI brain for you',
        'prov_sub'       => 'Switch provider without touching a single line of code. Match your budget & needs.',
        'prov_1'         => 'OpenRouter',
        'prov_1_sub'     => 'Recommended · access all models',
        'prov_2'         => 'OpenAI',
        'prov_2_sub'     => 'GPT-4o · GPT-4o-mini',
        'prov_3'         => 'Google Gemini',
        'prov_3_sub'     => '1.5 Flash · 1.5 Pro',
        'prov_4'         => 'DeepSeek',
        'prov_4_sub'     => 'Chat · Coder',
        /* testimonials */
        'testi_tag'      => 'Trusted By',
        'testi_h2'       => 'Loved by businesses worldwide',
        'testi_sub'      => 'See what our users are saying about ChatPopup.AI.',
        'testi_1_q'      => '"Set up in literally 4 minutes. My support load dropped 60% in the first week. The AI actually understands context — it feels like a real assistant."',
        'testi_1_name'   => 'Alex R.',
        'testi_1_role'   => 'E-commerce Owner',
        'testi_2_q'      => '"We switched from a $200/mo chat SaaS to this. Same quality, fraction of the cost. The custom system prompt is a game changer."',
        'testi_2_name'   => 'Maria S.',
        'testi_2_role'   => 'SaaS Founder',
        'testi_3_q'      => '"The Telegram notification is brilliant. I close leads from my phone now, knowing exactly when visitors are chatting."',
        'testi_3_name'   => 'James K.',
        'testi_3_role'   => 'Digital Marketer',
        /* cta + footer */
        'cta_h2'         => "Give your website\nan AI brain",
        'cta_p'          => 'Sign up free. No credit card. Ready in minutes.',
        'cta_btn'        => 'Create Free Account',
        'footer_built'   => 'Built on PHP 8 · Hosted on Hostinger',
        'footer_login'   => 'Login',
        'footer_reg'     => 'Register',
    ],

    /* ══ INDONESIAN ════════════════════════════════════════════════ */
    'id' => [
        'html_lang'      => 'id',
        'dir'            => 'ltr',
        'page_title'     => 'ChatPopup.AI — Widget Chat AI untuk Website Anda',
        'page_desc'      => 'Pasang widget chat AI di website dalam 5 menit. Multi-provider, custom branding, memori percakapan.',
        'nav_features'   => 'Fitur',
        'nav_how'        => 'Cara Kerja',
        'nav_providers'  => 'Provider',
        'nav_login'      => 'Masuk',
        'nav_register'   => 'Daftar Gratis',
        'hero_eyebrow'   => 'Trial Gratis · Tanpa Kartu Kredit',
        'hero_h1_a'      => 'Asisten AI',
        'hero_h1_b'      => 'di website Anda',
        'typewords'      => 'dalam 5 menit|tanpa coding|untuk siapa saja',
        'hero_p'         => 'Satu baris kode. Semua provider AI didukung. Warna, persona, dan instruksi bot sesuai brand Anda — diatur dari dashboard.',
        'cta_start'      => 'Mulai Gratis',
        'cta_login'      => 'Sudah punya akun',
        'trust_1'        => 'Setup 5 menit',
        'trust_2'        => 'Tanpa coding',
        'trust_3'        => 'Custom brand',
        'float_1'        => 'Pesan dijawab',
        'float_2'        => 'Aman & Encrypted',
        'mock_bot'       => 'Halo! Ada yang bisa saya bantu?',
        'mock_user'      => 'Saya mau tanya produk ini',
        'tick_items'     => 'OpenAI GPT-4o|Google Gemini|DeepSeek Chat|OpenRouter|Enkripsi AES-256|Setup 5 menit|Tanpa coding|6 bahasa|Memori chat|Notif Telegram',
        'stat_1_v'       => '5', 'stat_1_suf' => ' mnt', 'stat_1_lbl' => 'Waktu setup rata-rata',
        'stat_2_v'       => '4', 'stat_2_suf' => '',     'stat_2_lbl' => 'AI provider didukung',
        'stat_3_v'       => '1', 'stat_3_suf' => ' baris','stat_3_lbl' => 'Untuk pasang widget',
        'stat_4_v'       => '99.9','stat_4_suf'=> '%',   'stat_4_lbl' => 'Uptime SLA',
        'feat_tag'       => 'Fitur Unggulan',
        'feat_h2'        => "Semua yang Anda butuhkan,\nsiap dari hari pertama",
        'feat_sub'       => 'Dari setup hingga percakapan AI berkonteks, semuanya bisa diatur sendiri dari dashboard.',
        'feat_1_h'       => 'Pasang dalam 5 Menit',
        'feat_1_p'       => 'Copy satu baris script dari dashboard, tempel ke website. Widget langsung muncul.',
        'feat_2_h'       => 'Multi-Provider AI',
        'feat_2_p'       => 'OpenRouter, OpenAI, Gemini, DeepSeek. Ganti provider kapan saja dari dropdown.',
        'feat_3_h'       => 'Fully Customizable',
        'feat_3_p'       => 'Warna, nama bot, welcome message, system prompt — semua ikuti brand Anda.',
        'feat_4_h'       => 'Memori Percakapan',
        'feat_4_p'       => 'AI mengingat konteks dalam satu sesi. Pengunjung tidak perlu mengulang.',
        'feat_5_h'       => 'Notifikasi Telegram',
        'feat_5_p'       => 'Tahu setiap ada pesan masuk lewat bot Telegram — tanpa buka dashboard.',
        'feat_6_h'       => 'Aman & Terisolasi',
        'feat_6_p'       => 'Shadow DOM melindungi CSS widget. API key AI dienkripsi AES-256-GCM.',
        'how_tag'        => 'Cara Kerja',
        'how_h2'         => 'Tiga langkah, widget AI aktif',
        'how_sub'        => 'Tidak perlu keahlian teknis. Kalau bisa copy-paste, Anda bisa pakai ini.',
        'step_1_h'       => 'Daftar & Atur',
        'step_1_p'       => 'Pilih provider AI, masukkan API key, tulis system prompt sesuai bisnis.',
        'step_2_h'       => 'Copy Kode Embed',
        'step_2_p'       => 'Dashboard menghasilkan satu baris script unik. Satu klik, tersalin.',
        'step_3_h'       => 'Tempel ke Website',
        'step_3_p'       => 'Paste sebelum &lt;/body&gt; di WordPress atau landing page mana saja.',
        'prov_tag'       => 'Provider AI',
        'prov_h2'        => 'Pilih otak AI terbaik untuk Anda',
        'prov_sub'       => 'Ganti provider kapan saja tanpa coding. Cocok budget & kebutuhan Anda.',
        'prov_1'         => 'OpenRouter',       'prov_1_sub' => 'Rekomendasi · akses semua model',
        'prov_2'         => 'OpenAI',           'prov_2_sub' => 'GPT-4o · GPT-4o-mini',
        'prov_3'         => 'Google Gemini',    'prov_3_sub' => '1.5 Flash · 1.5 Pro',
        'prov_4'         => 'DeepSeek',         'prov_4_sub' => 'Chat · Coder',
        'testi_tag'      => 'Dipercaya Oleh',
        'testi_h2'       => 'Disukai bisnis di seluruh dunia',
        'testi_sub'      => 'Apa yang dikatakan pengguna kami tentang ChatPopup.AI.',
        'testi_1_q'      => '"Setup 4 menit, support turun 60% minggu pertama. AI benar-benar paham konteks."',
        'testi_1_name'   => 'Alex R.', 'testi_1_role' => 'Pemilik E-commerce',
        'testi_2_q'      => '"Kami pindah dari SaaS chat mahal ke ini. Kualitas sama, harga jauh lebih murah."',
        'testi_2_name'   => 'Maria S.', 'testi_2_role' => 'Founder SaaS',
        'testi_3_q'      => '"Notifikasi Telegram luar biasa. Sekarang closing lead dari HP kapan saja."',
        'testi_3_name'   => 'James K.', 'testi_3_role' => 'Digital Marketer',
        'cta_h2'         => "Saatnya beri website Anda\notak AI",
        'cta_p'          => 'Daftar gratis. Tidak perlu kartu kredit. Siap dalam hitungan menit.',
        'cta_btn'        => 'Buat Akun Gratis',
        'footer_built'   => 'Dibangun di atas PHP 8 · Hosted on Hostinger',
        'footer_login'   => 'Login',
        'footer_reg'     => 'Daftar',
    ],

    /* ══ SPANISH ════════════════════════════════════════════════ */
    'es' => [
        'html_lang'      => 'es', 'dir' => 'ltr',
        'page_title'     => 'ChatPopup.AI — Widget de Chat IA para tu Sitio',
        'page_desc'      => 'Añade un widget de chat IA en 5 minutos. Multi-proveedor, marca personalizada, memoria de conversación.',
        'nav_features'   => 'Funciones',  'nav_how' => 'Cómo Funciona',
        'nav_providers'  => 'Proveedores','nav_login' => 'Iniciar Sesión',
        'nav_register'   => 'Empezar Gratis',
        'hero_eyebrow'   => 'Prueba Gratis · Sin Tarjeta',
        'hero_h1_a'      => 'Asistente IA',
        'hero_h1_b'      => 'para tu sitio web',
        'typewords'      => 'en 5 minutos|sin código|para cualquiera',
        'hero_p'         => 'Una línea de código. Todos los proveedores soportados. Colores, persona e instrucciones del bot — gestionado desde el panel.',
        'cta_start'      => 'Empezar Gratis',
        'cta_login'      => 'Ya tengo cuenta',
        'trust_1'        => 'Listo en 5 min', 'trust_2' => 'Sin código', 'trust_3' => 'Marca propia',
        'float_1'        => 'Respuesta inmediata', 'float_2' => 'Seguro & Cifrado',
        'mock_bot'       => '¡Hola! ¿En qué puedo ayudarte?',
        'mock_user'      => 'Cuéntame sobre tu producto',
        'tick_items'     => 'OpenAI GPT-4o|Google Gemini|DeepSeek Chat|OpenRouter|Cifrado AES-256|Setup 5 min|Sin código|6 idiomas|Memoria chat|Alertas Telegram',
        'stat_1_v' => '5',    'stat_1_suf' => ' min',  'stat_1_lbl' => 'Tiempo de config. promedio',
        'stat_2_v' => '4',    'stat_2_suf' => '',      'stat_2_lbl' => 'Proveedores IA soportados',
        'stat_3_v' => '1',    'stat_3_suf' => ' línea', 'stat_3_lbl' => 'Para integrar el widget',
        'stat_4_v' => '99.9', 'stat_4_suf' => '%',     'stat_4_lbl' => 'SLA de disponibilidad',
        'feat_tag'       => 'Características',
        'feat_h2'        => "Todo lo que necesitas,\nlisto desde el primer día",
        'feat_sub'       => 'Desde la configuración hasta conversaciones IA contextuales — todo autoservicio.',
        'feat_1_h' => 'En vivo en 5 minutos',    'feat_1_p' => 'Copia un script tag, pégalo en tu sitio. El widget aparece al instante.',
        'feat_2_h' => 'Multi-Proveedor IA',       'feat_2_p' => 'OpenRouter, OpenAI, Gemini, DeepSeek. Cambia proveedor con un dropdown.',
        'feat_3_h' => 'Totalmente Personalizable','feat_3_p' => 'Color, nombre del bot, mensaje de bienvenida, prompt — todo tu marca.',
        'feat_4_h' => 'Memoria de Conversación',  'feat_4_p' => 'La IA recuerda el contexto de la sesión. Los visitantes no se repiten.',
        'feat_5_h' => 'Alertas de Telegram',      'feat_5_p' => 'Notificación por Telegram con cada nuevo mensaje — sin abrir el panel.',
        'feat_6_h' => 'Seguro y Aislado',          'feat_6_p' => 'Shadow DOM protege el CSS. Las claves API se cifran AES-256-GCM.',
        'how_tag'        => 'Cómo Funciona',
        'how_h2'         => 'Tres pasos. Widget IA activo.',
        'how_sub'        => 'Sin expertise técnico. Si puedes copiar-pegar, puedes usar esto.',
        'step_1_h' => 'Regístrate y Configura', 'step_1_p' => 'Elige proveedor, ingresa API key, escribe un prompt del sistema.',
        'step_2_h' => 'Copia el Código',          'step_2_p' => 'El panel genera un script tag único. Un clic, copiado al portapapeles.',
        'step_3_h' => 'Pégalo en tu Sitio',       'step_3_p' => 'Pega antes de &lt;/body&gt; en WordPress o cualquier landing page.',
        'prov_tag' => 'Proveedores IA', 'prov_h2' => 'El mejor cerebro IA para ti',
        'prov_sub' => 'Cambia de proveedor sin tocar código. Ajusta tu presupuesto.',
        'prov_1' => 'OpenRouter', 'prov_1_sub' => 'Recomendado · todos los modelos',
        'prov_2' => 'OpenAI',     'prov_2_sub' => 'GPT-4o · GPT-4o-mini',
        'prov_3' => 'Google Gemini','prov_3_sub' => '1.5 Flash · 1.5 Pro',
        'prov_4' => 'DeepSeek',   'prov_4_sub' => 'Chat · Coder',
        'testi_tag' => 'Confiado Por', 'testi_h2' => 'Amado por negocios en todo el mundo',
        'testi_sub' => 'Lo que dicen nuestros usuarios.',
        'testi_1_q' => '"Configurado en 4 minutos. Mi soporte cayó 60% en la primera semana."',
        'testi_1_name' => 'Alex R.', 'testi_1_role' => 'Dueño E-commerce',
        'testi_2_q' => '"Pasamos de un SaaS de $200/mes a esto. Misma calidad, mucho más barato."',
        'testi_2_name' => 'Maria S.', 'testi_2_role' => 'Fundadora SaaS',
        'testi_3_q' => '"La notificación de Telegram es brillante. Cierro prospectos desde el móvil."',
        'testi_3_name' => 'James K.', 'testi_3_role' => 'Marketing Digital',
        'cta_h2'    => "Dale a tu sitio\nun cerebro IA",
        'cta_p'     => 'Regístrate gratis. Sin tarjeta. Listo en minutos.',
        'cta_btn'   => 'Crear Cuenta Gratis',
        'footer_built' => 'Construido en PHP 8 · Alojado en Hostinger',
        'footer_login' => 'Login', 'footer_reg' => 'Registro',
    ],

    /* ══ FRENCH ════════════════════════════════════════════════ */
    'fr' => [
        'html_lang'      => 'fr', 'dir' => 'ltr',
        'page_title'     => 'ChatPopup.AI — Widget Chat IA pour votre Site',
        'page_desc'      => 'Ajoutez un widget chat IA en 5 minutes. Multi-fournisseur, marque personnalisée, mémoire de conversation.',
        'nav_features'   => 'Fonctionnalités', 'nav_how' => 'Comment ça marche',
        'nav_providers'  => 'Fournisseurs',    'nav_login' => 'Connexion',
        'nav_register'   => 'Commencer Gratuitement',
        'hero_eyebrow'   => 'Essai Gratuit · Sans CB',
        'hero_h1_a'      => 'Assistant IA',
        'hero_h1_b'      => 'pour votre site web',
        'typewords'      => 'en 5 minutes|sans code|pour tous',
        'hero_p'         => "Une ligne de code. Tous les fournisseurs d'IA supportés. Couleurs, persona et instructions — géré depuis le tableau de bord.",
        'cta_start'      => 'Commencer Gratuitement',
        'cta_login'      => "J'ai déjà un compte",
        'trust_1' => 'Prêt en 5 min', 'trust_2' => 'Sans code', 'trust_3' => 'Marque custom',
        'float_1' => 'Réponse immédiate', 'float_2' => 'Sécurisé & Chiffré',
        'mock_bot'  => 'Bonjour ! Comment puis-je vous aider ?',
        'mock_user' => 'Parlez-moi de votre produit',
        'tick_items' => 'OpenAI GPT-4o|Google Gemini|DeepSeek Chat|OpenRouter|Chiffrement AES-256|Setup 5 min|Sans code|6 langues|Mémoire chat|Alertes Telegram',
        'stat_1_v' => '5',    'stat_1_suf' => ' min',  'stat_1_lbl' => 'Temps de config. moyen',
        'stat_2_v' => '4',    'stat_2_suf' => '',      'stat_2_lbl' => "Fournisseurs d'IA",
        'stat_3_v' => '1',    'stat_3_suf' => ' ligne', 'stat_3_lbl' => "Pour intégrer le widget",
        'stat_4_v' => '99.9', 'stat_4_suf' => '%',     'stat_4_lbl' => 'Disponibilité SLA',
        'feat_tag' => 'Fonctionnalités Clés',
        'feat_h2'  => "Tout ce dont vous avez besoin,\nprêt dès le premier jour",
        'feat_sub' => "De la configuration aux conversations IA contextuelles — tout en libre-service.",
        'feat_1_h' => 'En ligne en 5 minutes',    'feat_1_p' => 'Copiez un script tag, collez-le. Le widget apparaît instantanément.',
        'feat_2_h' => 'Multi-Fournisseur IA',      'feat_2_p' => 'OpenRouter, OpenAI, Gemini, DeepSeek. Changez depuis un menu.',
        'feat_3_h' => 'Entièrement Personnalisable','feat_3_p' => 'Couleur, nom du bot, message de bienvenue, prompt système.',
        'feat_4_h' => 'Mémoire de Conversation',   'feat_4_p' => "L'IA se souvient du contexte. Les visiteurs ne se répètent pas.",
        'feat_5_h' => 'Alertes Telegram',           'feat_5_p' => 'Notifié via Telegram à chaque nouveau message.',
        'feat_6_h' => 'Sécurisé et Isolé',          'feat_6_p' => 'Shadow DOM protège le CSS. Clés API chiffrées AES-256-GCM.',
        'how_tag'  => 'Comment ça marche',
        'how_h2'   => 'Trois étapes. Widget IA actif.',
        'how_sub'  => 'Aucune expertise technique. Si vous savez copier-coller, vous pouvez utiliser ceci.',
        'step_1_h' => "S'inscrire et Configurer",  'step_1_p' => "Choisissez un fournisseur, entrez une clé API, rédigez un prompt.",
        'step_2_h' => 'Copier le Code',             'step_2_p' => 'Le tableau de bord génère un script tag unique. Un clic, copié.',
        'step_3_h' => 'Coller sur votre Site',      'step_3_p' => 'Collez avant &lt;/body&gt; dans WordPress ou toute landing page.',
        'prov_tag' => "Fournisseurs d'IA", 'prov_h2' => 'Le meilleur cerveau IA pour vous',
        'prov_sub' => 'Changez de fournisseur sans code. Adaptez votre budget.',
        'prov_1' => 'OpenRouter', 'prov_1_sub' => 'Recommandé · tous les modèles',
        'prov_2' => 'OpenAI',     'prov_2_sub' => 'GPT-4o · GPT-4o-mini',
        'prov_3' => 'Google Gemini','prov_3_sub' => '1.5 Flash · 1.5 Pro',
        'prov_4' => 'DeepSeek',   'prov_4_sub' => 'Chat · Coder',
        'testi_tag' => 'Ils nous font confiance', 'testi_h2' => 'Adoré par les entreprises du monde entier',
        'testi_sub' => 'Ce que disent nos utilisateurs.',
        'testi_1_q' => '"Configuré en 4 minutes. Mes tickets support ont baissé de 60% la première semaine."',
        'testi_1_name' => 'Alex R.', 'testi_1_role' => 'Propriétaire e-commerce',
        'testi_2_q' => '"Nous avons quitté un SaaS à 200€/mois pour ça. Même qualité, moins cher."',
        'testi_2_name' => 'Maria S.', 'testi_2_role' => 'Fondatrice SaaS',
        'testi_3_q' => '"La notification Telegram est brillante. Je close des leads depuis mon téléphone."',
        'testi_3_name' => 'James K.', 'testi_3_role' => 'Marketing Digital',
        'cta_h2'  => "Donnez un cerveau IA\nà votre site",
        'cta_p'   => "Inscription gratuite. Sans carte. Prêt en quelques minutes.",
        'cta_btn' => 'Créer un compte gratuit',
        'footer_built' => 'Construit sur PHP 8 · Hébergé sur Hostinger',
        'footer_login' => 'Connexion', 'footer_reg' => 'Inscription',
    ],

    /* ══ PORTUGUESE ════════════════════════════════════════════════ */
    'pt' => [
        'html_lang'      => 'pt', 'dir' => 'ltr',
        'page_title'     => 'ChatPopup.AI — Widget de Chat IA para seu Site',
        'page_desc'      => 'Adicione um widget de chat IA em 5 minutos. Multi-provedor, marca personalizada, memória de conversa.',
        'nav_features'   => 'Recursos', 'nav_how' => 'Como Funciona',
        'nav_providers'  => 'Provedores','nav_login' => 'Entrar',
        'nav_register'   => 'Começar Grátis',
        'hero_eyebrow'   => 'Trial Grátis · Sem Cartão',
        'hero_h1_a'      => 'Assistente IA',
        'hero_h1_b'      => 'para o seu site',
        'typewords'      => 'em 5 minutos|sem código|para todos',
        'hero_p'         => 'Uma linha de código. Todos os provedores de IA suportados. Cores, persona e instruções — gerenciado pelo painel.',
        'cta_start'      => 'Começar Grátis',
        'cta_login'      => 'Já tenho conta',
        'trust_1' => 'Setup em 5 min', 'trust_2' => 'Sem código', 'trust_3' => 'Marca própria',
        'float_1' => 'Resposta imediata', 'float_2' => 'Seguro & Criptografado',
        'mock_bot'  => 'Olá! Como posso ajudar?',
        'mock_user' => 'Fale sobre este produto',
        'tick_items' => 'OpenAI GPT-4o|Google Gemini|DeepSeek Chat|OpenRouter|Criptografia AES-256|Setup 5 min|Sem código|6 idiomas|Memória chat|Alertas Telegram',
        'stat_1_v' => '5',    'stat_1_suf' => ' min',  'stat_1_lbl' => 'Tempo médio de configuração',
        'stat_2_v' => '4',    'stat_2_suf' => '',      'stat_2_lbl' => 'Provedores IA suportados',
        'stat_3_v' => '1',    'stat_3_suf' => ' linha', 'stat_3_lbl' => 'Para incorporar o widget',
        'stat_4_v' => '99.9', 'stat_4_suf' => '%',     'stat_4_lbl' => 'SLA de uptime',
        'feat_tag' => 'Recursos Principais',
        'feat_h2'  => "Tudo que você precisa,\npronto desde o primeiro dia",
        'feat_sub' => 'Do setup às conversas com IA contextual — autogerenciado pelo painel.',
        'feat_1_h' => 'No Ar em 5 Minutos',    'feat_1_p' => 'Copie uma tag de script, cole no site. Widget aparece instantaneamente.',
        'feat_2_h' => 'Multi-Provedor IA',      'feat_2_p' => 'OpenRouter, OpenAI, Gemini, DeepSeek. Troque de provedor com dropdown.',
        'feat_3_h' => 'Totalmente Personalizável','feat_3_p' => 'Cor, nome do bot, mensagem de boas-vindas, prompt — tudo sua marca.',
        'feat_4_h' => 'Memória de Conversa',    'feat_4_p' => 'A IA lembra do contexto. Visitantes não precisam se repetir.',
        'feat_5_h' => 'Alertas no Telegram',    'feat_5_p' => 'Notificado via Telegram a cada nova mensagem.',
        'feat_6_h' => 'Seguro e Isolado',        'feat_6_p' => 'Shadow DOM protege o CSS. Chaves API criptografadas AES-256-GCM.',
        'how_tag'  => 'Como Funciona',
        'how_h2'   => 'Três etapas. Widget IA ativo.',
        'how_sub'  => 'Sem expertise técnica. Se você sabe copiar e colar, pode usar isso.',
        'step_1_h' => 'Cadastre e Configure', 'step_1_p' => 'Escolha provedor IA, insira API key, escreva um prompt.',
        'step_2_h' => 'Copie o Código',        'step_2_p' => 'O painel gera um script tag único. Um clique, copiado.',
        'step_3_h' => 'Cole no seu Site',      'step_3_p' => 'Cole antes de &lt;/body&gt; no WordPress ou qualquer landing page.',
        'prov_tag' => 'Provedores IA', 'prov_h2' => 'O melhor cérebro IA para você',
        'prov_sub' => 'Troque de provedor sem código. Ajuste ao seu orçamento.',
        'prov_1' => 'OpenRouter', 'prov_1_sub' => 'Recomendado · todos os modelos',
        'prov_2' => 'OpenAI',     'prov_2_sub' => 'GPT-4o · GPT-4o-mini',
        'prov_3' => 'Google Gemini','prov_3_sub' => '1.5 Flash · 1.5 Pro',
        'prov_4' => 'DeepSeek',   'prov_4_sub' => 'Chat · Coder',
        'testi_tag' => 'Confiado Por', 'testi_h2' => 'Adorado por empresas no mundo todo',
        'testi_sub' => 'Veja o que nossos usuários dizem.',
        'testi_1_q' => '"Configurado em 4 minutos. Meu suporte caiu 60% na primeira semana."',
        'testi_1_name' => 'Alex R.', 'testi_1_role' => 'Dono de E-commerce',
        'testi_2_q' => '"Migramos de um SaaS caro para isso. Mesma qualidade, muito mais barato."',
        'testi_2_name' => 'Maria S.', 'testi_2_role' => 'Fundadora SaaS',
        'testi_3_q' => '"A notificação do Telegram é brilhante. Fecho leads pelo celular agora."',
        'testi_3_name' => 'James K.', 'testi_3_role' => 'Marketing Digital',
        'cta_h2'  => "Dê ao seu site\num cérebro IA",
        'cta_p'   => 'Cadastre-se grátis. Sem cartão. Pronto em minutos.',
        'cta_btn' => 'Criar Conta Grátis',
        'footer_built' => 'Construído em PHP 8 · Hospedado na Hostinger',
        'footer_login' => 'Entrar', 'footer_reg' => 'Cadastro',
    ],

    /* ══ JAPANESE ════════════════════════════════════════════════ */
    'ja' => [
        'html_lang'      => 'ja', 'dir' => 'ltr',
        'page_title'     => 'ChatPopup.AI — ウェブサイト向けAIチャットウィジェット',
        'page_desc'      => '5分でAIチャットウィジェットを追加。マルチプロバイダー対応、カスタムブランド、会話メモリ付き。',
        'nav_features'   => '機能', 'nav_how' => '使い方',
        'nav_providers'  => 'プロバイダー', 'nav_login' => 'ログイン',
        'nav_register'   => '無料で始める',
        'hero_eyebrow'   => '無料トライアル · クレカ不要',
        'hero_h1_a'      => 'AIアシスタントを',
        'hero_h1_b'      => 'あなたのサイトへ',
        'typewords'      => '5分で完成|コード不要|誰でも使える',
        'hero_p'         => '1行のコードで導入完了。全AIプロバイダー対応。色・ペルソナ・ボット指示はダッシュボードから管理。',
        'cta_start'      => '無料で始める',
        'cta_login'      => 'アカウントをお持ちの方',
        'trust_1' => '5分でセットアップ', 'trust_2' => 'コード不要', 'trust_3' => 'ブランドカスタマイズ',
        'float_1' => '即時返信', 'float_2' => '安全・暗号化',
        'mock_bot'  => 'こんにちは！何かお手伝いできますか？',
        'mock_user' => '商品について教えてください',
        'tick_items' => 'OpenAI GPT-4o|Google Gemini|DeepSeek Chat|OpenRouter|AES-256暗号化|5分セットアップ|コード不要|6言語対応|チャット記憶|Telegram通知',
        'stat_1_v' => '5',    'stat_1_suf' => '分',   'stat_1_lbl' => '平均セットアップ時間',
        'stat_2_v' => '4',    'stat_2_suf' => '',      'stat_2_lbl' => '対応AIプロバイダー数',
        'stat_3_v' => '1',    'stat_3_suf' => '行',    'stat_3_lbl' => 'ウィジェット埋め込み',
        'stat_4_v' => '99.9', 'stat_4_suf' => '%',     'stat_4_lbl' => '稼働率SLA',
        'feat_tag' => '主な機能',
        'feat_h2'  => "必要なものがすべて\n初日から揃っています",
        'feat_sub' => 'セットアップからコンテキスト対応AI会話まで、すべてダッシュボードで自己管理。',
        'feat_1_h' => '5分で公開',            'feat_1_p' => 'スクリプトタグをコピーして貼り付けるだけ。ウィジェットが即座に表示されます。',
        'feat_2_h' => 'マルチプロバイダー対応','feat_2_p' => 'OpenRouter、OpenAI、Gemini、DeepSeek。ドロップダウンでいつでも切替。',
        'feat_3_h' => '完全カスタマイズ',      'feat_3_p' => 'カラー・ボット名・ウェルカムメッセージ・システムプロンプト設定可能。',
        'feat_4_h' => '会話メモリ',            'feat_4_p' => 'AIはセッション内のコンテキストを記憶。訪問者の繰り返し不要。',
        'feat_5_h' => 'Telegram通知',          'feat_5_p' => '新しいメッセージのたびにTelegramで通知。ダッシュボード不要。',
        'feat_6_h' => '安全・隔離',            'feat_6_p' => 'Shadow DOMがCSSを保護。APIキーはAES-256-GCMで暗号化。',
        'how_tag'  => '使い方',
        'how_h2'   => '3ステップでAIウィジェット起動',
        'how_sub'  => '技術知識は不要。コピー＆ペーストができれば使えます。',
        'step_1_h' => '登録・設定',            'step_1_p' => 'AIプロバイダーを選び、APIキーを入力し、システムプロンプトを作成。',
        'step_2_h' => '埋め込みコードをコピー','step_2_p' => 'ダッシュボードが固有のスクリプトタグを生成。ワンクリックでコピー。',
        'step_3_h' => 'サイトに貼り付け',      'step_3_p' => 'WordPressなどの&lt;/body&gt;前に貼り付けるだけ。',
        'prov_tag' => 'AIプロバイダー', 'prov_h2' => 'あなたに最適なAIを選ぼう',
        'prov_sub' => 'コード不要でプロバイダーを切り替え。予算とニーズに合わせて選択。',
        'prov_1' => 'OpenRouter',    'prov_1_sub' => 'おすすめ · 全モデルアクセス',
        'prov_2' => 'OpenAI',        'prov_2_sub' => 'GPT-4o · GPT-4o-mini',
        'prov_3' => 'Google Gemini', 'prov_3_sub' => '1.5 Flash · 1.5 Pro',
        'prov_4' => 'DeepSeek',      'prov_4_sub' => 'Chat · Coder',
        'testi_tag' => '利用実績', 'testi_h2' => '世界中のビジネスに愛用',
        'testi_sub' => 'ChatPopup.AIユーザーの声をご紹介します。',
        'testi_1_q' => '「文字通り4分でセットアップ完了。最初の週でサポート負荷が60%減りました。」',
        'testi_1_name' => 'Alex R.', 'testi_1_role' => 'EC事業オーナー',
        'testi_2_q' => '「高コストなチャットSaaSからこれに切り替えました。同じ品質で大幅コスト削減。」',
        'testi_2_name' => 'Maria S.', 'testi_2_role' => 'SaaS創業者',
        'testi_3_q' => '「Telegram通知は画期的。スマホからリードをクロージングできます。」',
        'testi_3_name' => 'James K.', 'testi_3_role' => 'デジタルマーケター',
        'cta_h2'  => "あなたのサイトに\nAIを搭載しよう",
        'cta_p'   => '無料登録。クレジットカード不要。数分で準備完了。',
        'cta_btn' => '無料アカウント作成',
        'footer_built' => 'PHP 8で構築 · Hostingerでホスティング',
        'footer_login' => 'ログイン', 'footer_reg' => '登録',
    ],

    ]; /* end $all */

    return $all[$lang] ?? $all['en'];
}
