<?php
declare(strict_types=1);
/**
 * ChatPopup.AI — i18n language strings
 * Usage: $t = lang_strings($lang); echo $t['hero_h1'];
 */

function get_lang(): string {
    $allowed = ['en','id','es','fr','pt','ja'];
    /* 1. Query param (highest priority) */
    if (!empty($_GET['lang'])) {
        $q = strtolower(trim((string)$_GET['lang']));
        if (in_array($q, $allowed, true)) {
            setcookie('cp_lang', $q, time()+60*60*24*365, '/', '', false, false);
            return $q;
        }
    }
    /* 2. Cookie */
    if (!empty($_COOKIE['cp_lang'])) {
        $c = strtolower(trim((string)$_COOKIE['cp_lang']));
        if (in_array($c, $allowed, true)) return $c;
    }
    /* 3. Browser Accept-Language */
    $accept = strtolower($_SERVER['HTTP_ACCEPT_LANGUAGE'] ?? '');
    foreach ($allowed as $l) {
        if (str_starts_with($accept, $l)) return $l;
    }
    return 'en'; /* default */
}

function lang_strings(string $lang): array {
    $all = [

    /* ────────────────── ENGLISH ────────────────── */
    'en' => [
        'html_lang'        => 'en',
        'page_title'       => 'ChatPopup.AI — AI Chat Widget for Any Website',
        'page_desc'        => 'Add an AI chat widget to your site in 5 minutes. Multi-provider (OpenAI, Gemini, DeepSeek, OpenRouter), custom branding, chat memory.',
        'dir'              => 'ltr',

        /* Nav */
        'nav_features'     => 'Features',
        'nav_how'          => 'How It Works',
        'nav_providers'    => 'Providers',
        'nav_login'        => 'Log In',
        'nav_register'     => 'Start Free',

        /* Hero */
        'hero_eyebrow'     => 'Free Trial · No Credit Card',
        'hero_h1_1'        => 'AI Assistant',
        'hero_h1_2'        => 'for your website',
        'typewriter_words' => 'in 5 minutes|without coding|for anyone',
        'hero_p'           => 'One line of code. All AI providers supported. Custom colors, persona & bot instructions — managed from dashboard, zero database access.',
        'hero_cta1'        => 'Start Free',
        'hero_cta2'        => 'Already have account',
        'trust_1'          => '5-min setup',
        'trust_2'          => 'No coding',
        'trust_3'          => 'Custom brand',
        'float_1'          => 'Reply instant',
        'float_2'          => 'Secure & Encrypted',
        'mock_chat_bot'    => 'Hi! How can I help you today?',
        'mock_chat_user'   => 'Tell me about your product',

        /* Stats */
        'stat_1_num'       => '5 min',
        'stat_1_label'     => 'Average setup time',
        'stat_2_num'       => '4',
        'stat_2_label'     => 'AI providers supported',
        'stat_3_num'       => '1 line',
        'stat_3_label'     => 'To embed widget',
        'stat_4_num'       => '99.9%',
        'stat_4_label'     => 'Uptime SLA',

        /* Features */
        'feat_tag'         => 'Key Features',
        'feat_h2'          => "Everything you need,\nready from day one",
        'feat_sub'         => 'From setup to context-aware AI conversations — all self-managed from the dashboard.',
        'feat_1_h'         => 'Live in 5 Minutes',
        'feat_1_p'         => 'Copy one script tag from dashboard, paste to website. Widget appears instantly on every page.',
        'feat_2_h'         => 'Multi-Provider AI',
        'feat_2_p'         => 'OpenRouter, OpenAI, Gemini, DeepSeek. Switch provider anytime from a dropdown.',
        'feat_3_h'         => 'Fully Customizable',
        'feat_3_p'         => 'Primary color, bot name, welcome message, system prompt — all follow your brand.',
        'feat_4_h'         => 'Conversation Memory',
        'feat_4_p'         => 'AI remembers context in one session. Visitors never need to repeat themselves.',
        'feat_5_h'         => 'Telegram Alerts',
        'feat_5_p'         => 'Get notified via Telegram every time a new message arrives — no dashboard needed.',
        'feat_6_h'         => 'Secure & Isolated',
        'feat_6_p'         => 'Shadow DOM protects widget CSS. AI API keys are AES-256-GCM encrypted in the database.',

        /* How */
        'how_tag'          => 'How It Works',
        'how_h2'           => 'Three steps. AI widget live.',
        'how_sub'          => 'No technical expertise needed. If you can copy-paste, you can use this.',
        'step_1_h'         => 'Sign Up & Configure',
        'step_1_p'         => 'Choose AI provider, enter API key, write a system prompt for your business.',
        'step_2_h'         => 'Copy Embed Code',
        'step_2_p'         => 'Dashboard auto-generates a unique script tag. One click, copied to clipboard.',
        'step_3_h'         => 'Paste to Website',
        'step_3_p'         => 'Paste before </body> in WordPress or any landing page.',

        /* Providers */
        'prov_tag'         => 'AI Providers',
        'prov_h2'          => 'Pick the best AI brain for you',
        'prov_sub'         => 'Switch provider anytime without coding. Match your budget & requirements.',
        'prov_1'           => 'OpenRouter',
        'prov_1_tag'       => 'Recommended · access all models',
        'prov_2'           => 'OpenAI',
        'prov_2_tag'       => 'GPT-4o · GPT-4o-mini',
        'prov_3'           => 'Google Gemini',
        'prov_3_tag'       => '1.5 Flash · 1.5 Pro',
        'prov_4'           => 'DeepSeek',
        'prov_4_tag'       => 'Chat · Coder',

        /* Testimonial */
        'test_tag'         => 'Trusted By',
        'test_h2'          => 'Loved by businesses worldwide',
        'test_sub'         => 'See what our users are saying about ChatPopup.AI.',
        'test_1_body'      => '"Set up in literally 4 minutes. My support load dropped 60% in the first week. The AI actually understands context — it feels like a real assistant."',
        'test_1_name'      => 'Alex R.',
        'test_1_role'      => 'E-commerce Owner',
        'test_2_body'      => '"We switched from a $200/mo chat SaaS to this. Same quality, fraction of the cost. The custom system prompt is a game changer."',
        'test_2_name'      => 'Maria S.',
        'test_2_role'      => 'SaaS Founder',
        'test_3_body'      => '"The Telegram notification is brilliant. I close leads from my phone now, knowing exactly when visitors are chatting."',
        'test_3_name'      => 'James K.',
        'test_3_role'      => 'Digital Marketer',

        /* CTA */
        'cta_h2'           => "Give your website\nan AI brain",
        'cta_p'            => 'Sign up free. No credit card. Ready in minutes.',
        'cta_btn'          => 'Create Free Account',

        /* Footer */
        'footer_built'     => 'Built on PHP 8 · Hosted on Hostinger',
        'footer_login'     => 'Login',
        'footer_register'  => 'Register',
    ],

    /* ────────────────── INDONESIAN ────────────────── */
    'id' => [
        'html_lang'        => 'id',
        'page_title'       => 'ChatPopup.AI — Widget Chat AI untuk Website Anda',
        'page_desc'        => 'Pasang widget chat AI di website dalam 5 menit. Multi-provider (OpenAI, Gemini, DeepSeek, OpenRouter), custom branding, memori percakapan.',
        'dir'              => 'ltr',
        'nav_features'     => 'Fitur',
        'nav_how'          => 'Cara Kerja',
        'nav_providers'    => 'Provider',
        'nav_login'        => 'Masuk',
        'nav_register'     => 'Daftar Gratis',
        'hero_eyebrow'     => 'Trial Gratis · Tanpa Kartu Kredit',
        'hero_h1_1'        => 'Asisten AI',
        'hero_h1_2'        => 'di website Anda',
        'typewriter_words' => 'dalam 5 menit|tanpa coding|untuk siapa saja',
        'hero_p'           => 'Satu baris kode. Semua provider AI didukung. Warna, persona, dan instruksi bot sesuai brand Anda — diatur dari dashboard.',
        'hero_cta1'        => 'Mulai Gratis',
        'hero_cta2'        => 'Sudah punya akun',
        'trust_1'          => 'Setup 5 menit',
        'trust_2'          => 'Tanpa coding',
        'trust_3'          => 'Custom brand',
        'float_1'          => 'Pesan dijawab',
        'float_2'          => 'Aman & Encrypted',
        'mock_chat_bot'    => 'Halo! Ada yang bisa saya bantu?',
        'mock_chat_user'   => 'Tanya soal produk ini',
        'stat_1_num'       => '5 menit',
        'stat_1_label'     => 'Waktu setup rata-rata',
        'stat_2_num'       => '4',
        'stat_2_label'     => 'AI provider didukung',
        'stat_3_num'       => '1 baris',
        'stat_3_label'     => 'Untuk pasang widget',
        'stat_4_num'       => '99.9%',
        'stat_4_label'     => 'Uptime SLA',
        'feat_tag'         => 'Fitur Unggulan',
        'feat_h2'          => "Semua yang Anda butuhkan,\nsiap dari hari pertama",
        'feat_sub'         => 'Dari setup hingga percakapan AI berkonteks, semuanya bisa diatur dari dashboard.',
        'feat_1_h'         => 'Pasang dalam 5 Menit',
        'feat_1_p'         => 'Copy satu baris script dari dashboard, tempel ke website. Widget langsung muncul.',
        'feat_2_h'         => 'Multi-Provider AI',
        'feat_2_p'         => 'OpenRouter, OpenAI, Gemini, DeepSeek. Ganti provider kapan saja dari dropdown.',
        'feat_3_h'         => 'Fully Customizable',
        'feat_3_p'         => 'Warna, nama bot, welcome message, system prompt — semua ikuti brand Anda.',
        'feat_4_h'         => 'Memori Percakapan',
        'feat_4_p'         => 'AI mengingat konteks dalam satu sesi. Pengunjung tidak perlu mengulang.',
        'feat_5_h'         => 'Notifikasi Telegram',
        'feat_5_p'         => 'Tahu setiap ada pesan masuk lewat bot Telegram — tanpa buka dashboard.',
        'feat_6_h'         => 'Aman & Terisolasi',
        'feat_6_p'         => 'Shadow DOM melindungi CSS widget. API key AI dienkripsi AES-256-GCM.',
        'how_tag'          => 'Cara Kerja',
        'how_h2'           => 'Tiga langkah, widget AI aktif',
        'how_sub'          => 'Tidak perlu keahlian teknis. Kalau bisa copy-paste, Anda bisa pakai ini.',
        'step_1_h'         => 'Daftar & Atur',
        'step_1_p'         => 'Pilih provider AI, masukkan API key, tulis system prompt sesuai bisnis.',
        'step_2_h'         => 'Copy Kode Embed',
        'step_2_p'         => 'Dashboard menghasilkan satu baris script unik. Satu klik, tersalin.',
        'step_3_h'         => 'Tempel ke Website',
        'step_3_p'         => 'Paste sebelum </body> di WordPress atau landing page mana saja.',
        'prov_tag'         => 'Provider AI',
        'prov_h2'          => 'Pilih otak AI terbaik untuk Anda',
        'prov_sub'         => 'Ganti provider kapan saja tanpa coding. Cocok budget & kebutuhan Anda.',
        'prov_1'           => 'OpenRouter',
        'prov_1_tag'       => 'Rekomendasi · akses semua model',
        'prov_2'           => 'OpenAI',
        'prov_2_tag'       => 'GPT-4o · GPT-4o-mini',
        'prov_3'           => 'Google Gemini',
        'prov_3_tag'       => '1.5 Flash · 1.5 Pro',
        'prov_4'           => 'DeepSeek',
        'prov_4_tag'       => 'Chat · Coder',
        'test_tag'         => 'Dipercaya Oleh',
        'test_h2'          => 'Disukai bisnis di seluruh dunia',
        'test_sub'         => 'Apa yang dikatakan pengguna kami tentang ChatPopup.AI.',
        'test_1_body'      => '"Setup 4 menit, support saya turun 60% di minggu pertama. AI benar-benar paham konteks."',
        'test_1_name'      => 'Alex R.',
        'test_1_role'      => 'Pemilik E-commerce',
        'test_2_body'      => '"Kami pindah dari SaaS chat Rp 3jt/bulan ke ini. Kualitas sama, harga jauh lebih murah."',
        'test_2_name'      => 'Maria S.',
        'test_2_role'      => 'Founder SaaS',
        'test_3_body'      => '"Notifikasi Telegram luar biasa. Sekarang saya closing lead dari HP kapan saja."',
        'test_3_name'      => 'James K.',
        'test_3_role'      => 'Digital Marketer',
        'cta_h2'           => "Saatnya beri website Anda\notak AI",
        'cta_p'            => 'Daftar gratis. Tidak perlu kartu kredit. Siap dalam hitungan menit.',
        'cta_btn'          => 'Buat Akun Gratis',
        'footer_built'     => 'Dibangun di atas PHP 8 · Hosted on Hostinger',
        'footer_login'     => 'Login',
        'footer_register'  => 'Daftar',
    ],

    /* ────────────────── SPANISH ────────────────── */
    'es' => [
        'html_lang'        => 'es',
        'page_title'       => 'ChatPopup.AI — Widget de Chat IA para tu Sitio Web',
        'page_desc'        => 'Añade un widget de chat IA a tu sitio en 5 minutos. Multi-proveedor, marca personalizada, memoria de conversación.',
        'dir'              => 'ltr',
        'nav_features'     => 'Funciones',
        'nav_how'          => 'Cómo Funciona',
        'nav_providers'    => 'Proveedores',
        'nav_login'        => 'Iniciar Sesión',
        'nav_register'     => 'Empezar Gratis',
        'hero_eyebrow'     => 'Prueba Gratis · Sin Tarjeta',
        'hero_h1_1'        => 'Asistente IA',
        'hero_h1_2'        => 'para tu sitio web',
        'typewriter_words' => 'en 5 minutos|sin código|para cualquiera',
        'hero_p'           => 'Una línea de código. Todos los proveedores de IA soportados. Colores, persona e instrucciones del bot — administrado desde el panel.',
        'hero_cta1'        => 'Empezar Gratis',
        'hero_cta2'        => 'Ya tengo cuenta',
        'trust_1'          => 'Listo en 5 min',
        'trust_2'          => 'Sin código',
        'trust_3'          => 'Marca propia',
        'float_1'          => 'Respuesta instant.',
        'float_2'          => 'Seguro & Cifrado',
        'mock_chat_bot'    => '¡Hola! ¿En qué puedo ayudarte?',
        'mock_chat_user'   => 'Cuéntame sobre tu producto',
        'stat_1_num'       => '5 min',
        'stat_1_label'     => 'Tiempo promedio de configuración',
        'stat_2_num'       => '4',
        'stat_2_label'     => 'Proveedores de IA soportados',
        'stat_3_num'       => '1 línea',
        'stat_3_label'     => 'Para integrar el widget',
        'stat_4_num'       => '99.9%',
        'stat_4_label'     => 'SLA de uptime',
        'feat_tag'         => 'Características',
        'feat_h2'          => "Todo lo que necesitas,\nlisto desde el primer día",
        'feat_sub'         => 'Desde la configuración hasta las conversaciones con IA contextual, todo autoservicio desde el panel.',
        'feat_1_h'         => 'En Vivo en 5 Minutos',
        'feat_1_p'         => 'Copia una etiqueta de script del panel, pégala en tu sitio. El widget aparece instantáneamente.',
        'feat_2_h'         => 'Multi-Proveedor IA',
        'feat_2_p'         => 'OpenRouter, OpenAI, Gemini, DeepSeek. Cambia de proveedor en cualquier momento.',
        'feat_3_h'         => 'Totalmente Personalizable',
        'feat_3_p'         => 'Color, nombre del bot, mensaje de bienvenida, prompt del sistema — todo siguiendo tu marca.',
        'feat_4_h'         => 'Memoria de Conversación',
        'feat_4_p'         => 'La IA recuerda el contexto en una sesión. Los visitantes nunca tienen que repetirse.',
        'feat_5_h'         => 'Alertas de Telegram',
        'feat_5_p'         => 'Recibe notificaciones via Telegram cada vez que llegue un nuevo mensaje.',
        'feat_6_h'         => 'Seguro y Aislado',
        'feat_6_p'         => 'Shadow DOM protege el CSS del widget. Las claves de API se cifran con AES-256-GCM.',
        'how_tag'          => 'Cómo Funciona',
        'how_h2'           => 'Tres pasos. Widget IA activo.',
        'how_sub'          => 'No se necesita experiencia técnica. Si puedes copiar y pegar, puedes usar esto.',
        'step_1_h'         => 'Regístrate y Configura',
        'step_1_p'         => 'Elige proveedor IA, ingresa API key, escribe un prompt del sistema para tu negocio.',
        'step_2_h'         => 'Copia el Código',
        'step_2_p'         => 'El panel genera un script tag único. Un clic, copiado al portapapeles.',
        'step_3_h'         => 'Pégalo en tu Sitio',
        'step_3_p'         => 'Pega antes del </body> en WordPress o cualquier landing page.',
        'prov_tag'         => 'Proveedores de IA',
        'prov_h2'          => 'Elige el mejor cerebro IA para ti',
        'prov_sub'         => 'Cambia de proveedor sin código. Ajusta tu presupuesto y necesidades.',
        'prov_1'           => 'OpenRouter',
        'prov_1_tag'       => 'Recomendado · acceso a todos',
        'prov_2'           => 'OpenAI',
        'prov_2_tag'       => 'GPT-4o · GPT-4o-mini',
        'prov_3'           => 'Google Gemini',
        'prov_3_tag'       => '1.5 Flash · 1.5 Pro',
        'prov_4'           => 'DeepSeek',
        'prov_4_tag'       => 'Chat · Coder',
        'test_tag'         => 'Confiado Por',
        'test_h2'          => 'Amado por negocios en todo el mundo',
        'test_sub'         => 'Lo que dicen nuestros usuarios sobre ChatPopup.AI.',
        'test_1_body'      => '"Configurado en literalmente 4 minutos. Mi carga de soporte bajó 60% en la primera semana."',
        'test_1_name'      => 'Alex R.',
        'test_1_role'      => 'Dueño E-commerce',
        'test_2_body'      => '"Pasamos de un SaaS de chat de $200/mes a esto. Misma calidad, fracción del costo."',
        'test_2_name'      => 'Maria S.',
        'test_2_role'      => 'Fundadora SaaS',
        'test_3_body'      => '"La notificación de Telegram es brillante. Ahora cierro prospectos desde mi teléfono."',
        'test_3_name'      => 'James K.',
        'test_3_role'      => 'Marketing Digital',
        'cta_h2'           => "Dale a tu sitio\nun cerebro IA",
        'cta_p'            => 'Regístrate gratis. Sin tarjeta de crédito. Listo en minutos.',
        'cta_btn'          => 'Crear Cuenta Gratis',
        'footer_built'     => 'Construido en PHP 8 · Alojado en Hostinger',
        'footer_login'     => 'Login',
        'footer_register'  => 'Registro',
    ],

    /* ────────────────── FRENCH ────────────────── */
    'fr' => [
        'html_lang'        => 'fr',
        'page_title'       => 'ChatPopup.AI — Widget Chat IA pour Votre Site',
        'page_desc'        => 'Ajoutez un widget chat IA à votre site en 5 minutes. Multi-fournisseur, marque personnalisée, mémoire conversationnelle.',
        'dir'              => 'ltr',
        'nav_features'     => 'Fonctionnalités',
        'nav_how'          => 'Comment ça marche',
        'nav_providers'    => 'Fournisseurs',
        'nav_login'        => 'Connexion',
        'nav_register'     => 'Commencer Gratuitement',
        'hero_eyebrow'     => 'Essai Gratuit · Sans CB',
        'hero_h1_1'        => 'Assistant IA',
        'hero_h1_2'        => 'pour votre site web',
        'typewriter_words' => 'en 5 minutes|sans code|pour tous',
        'hero_p'           => "Une ligne de code. Tous les fournisseurs d'IA supportés. Couleurs, persona et instructions — géré depuis le tableau de bord.",
        'hero_cta1'        => 'Commencer Gratuitement',
        'hero_cta2'        => "J'ai déjà un compte",
        'trust_1'          => 'Prêt en 5 min',
        'trust_2'          => 'Sans code',
        'trust_3'          => 'Marque custom',
        'float_1'          => 'Réponse immédiate',
        'float_2'          => 'Sécurisé & Chiffré',
        'mock_chat_bot'    => 'Bonjour ! Comment puis-je vous aider ?',
        'mock_chat_user'   => 'Parlez-moi de votre produit',
        'stat_1_num'       => '5 min',
        'stat_1_label'     => 'Temps de configuration moyen',
        'stat_2_num'       => '4',
        'stat_2_label'     => "Fournisseurs d'IA supportés",
        'stat_3_num'       => '1 ligne',
        'stat_3_label'     => "Pour intégrer le widget",
        'stat_4_num'       => '99.9%',
        'stat_4_label'     => 'SLA de disponibilité',
        'feat_tag'         => 'Fonctionnalités Clés',
        'feat_h2'          => "Tout ce dont vous avez besoin,\nprêt dès le premier jour",
        'feat_sub'         => "De la configuration aux conversations IA contextuelles — tout en libre-service depuis le tableau de bord.",
        'feat_1_h'         => 'En ligne en 5 minutes',
        'feat_1_p'         => 'Copiez une balise script depuis le tableau de bord, collez-la. Le widget apparaît instantanément.',
        'feat_2_h'         => 'Multi-Fournisseur IA',
        'feat_2_p'         => 'OpenRouter, OpenAI, Gemini, DeepSeek. Changez de fournisseur depuis un menu déroulant.',
        'feat_3_h'         => 'Entièrement Personnalisable',
        'feat_3_p'         => 'Couleur, nom du bot, message de bienvenue, prompt système — tout suit votre marque.',
        'feat_4_h'         => 'Mémoire de Conversation',
        'feat_4_p'         => "L'IA se souvient du contexte dans une session. Les visiteurs n'ont pas à se répéter.",
        'feat_5_h'         => 'Alertes Telegram',
        'feat_5_p'         => 'Soyez notifié via Telegram à chaque nouveau message — sans ouvrir le tableau de bord.',
        'feat_6_h'         => 'Sécurisé et Isolé',
        'feat_6_p'         => 'Shadow DOM protège le CSS du widget. Les clés API sont chiffrées AES-256-GCM.',
        'how_tag'          => 'Comment ça marche',
        'how_h2'           => 'Trois étapes. Widget IA actif.',
        'how_sub'          => 'Aucune expertise technique requise. Si vous savez copier-coller, vous pouvez utiliser ceci.',
        'step_1_h'         => "S'inscrire et Configurer",
        'step_1_p'         => "Choisissez un fournisseur IA, entrez une clé API, rédigez un prompt système pour votre entreprise.",
        'step_2_h'         => 'Copier le Code',
        'step_2_p'         => 'Le tableau de bord génère automatiquement une balise script unique. Un clic, copié.',
        'step_3_h'         => 'Coller sur votre Site',
        'step_3_p'         => 'Collez avant </body> dans WordPress ou toute landing page.',
        'prov_tag'         => "Fournisseurs d'IA",
        'prov_h2'          => "Choisissez le meilleur cerveau IA",
        'prov_sub'         => "Changez de fournisseur sans code. Adaptez votre budget et vos besoins.",
        'prov_1'           => 'OpenRouter',
        'prov_1_tag'       => 'Recommandé · accès à tous',
        'prov_2'           => 'OpenAI',
        'prov_2_tag'       => 'GPT-4o · GPT-4o-mini',
        'prov_3'           => 'Google Gemini',
        'prov_3_tag'       => '1.5 Flash · 1.5 Pro',
        'prov_4'           => 'DeepSeek',
        'prov_4_tag'       => 'Chat · Coder',
        'test_tag'         => 'Ils nous font confiance',
        'test_h2'          => 'Adoré par les entreprises du monde entier',
        'test_sub'         => "Découvrez ce que disent nos utilisateurs de ChatPopup.AI.",
        'test_1_body'      => '"Configuré en 4 minutes. Mes tickets de support ont baissé de 60% la première semaine."',
        'test_1_name'      => 'Alex R.',
        'test_1_role'      => 'Propriétaire e-commerce',
        'test_2_body'      => '"Nous avons abandonné un SaaS de chat à 200€/mois pour ça. Même qualité, beaucoup moins cher."',
        'test_2_name'      => 'Maria S.',
        'test_2_role'      => 'Fondatrice SaaS',
        'test_3_body'      => '"La notification Telegram est brillante. Je close des leads depuis mon téléphone maintenant."',
        'test_3_name'      => 'James K.',
        'test_3_role'      => 'Marketing Digital',
        'cta_h2'           => "Donnez un cerveau IA\nà votre site",
        'cta_p'            => "Inscription gratuite. Sans carte de crédit. Prêt en quelques minutes.",
        'cta_btn'          => 'Créer un compte gratuit',
        'footer_built'     => 'Construit sur PHP 8 · Hébergé sur Hostinger',
        'footer_login'     => 'Connexion',
        'footer_register'  => 'Inscription',
    ],

    /* ────────────────── PORTUGUESE ────────────────── */
    'pt' => [
        'html_lang'        => 'pt',
        'page_title'       => 'ChatPopup.AI — Widget de Chat IA para seu Site',
        'page_desc'        => 'Adicione um widget de chat IA ao seu site em 5 minutos. Multi-provedor, marca personalizada, memória de conversa.',
        'dir'              => 'ltr',
        'nav_features'     => 'Recursos',
        'nav_how'          => 'Como Funciona',
        'nav_providers'    => 'Provedores',
        'nav_login'        => 'Entrar',
        'nav_register'     => 'Começar Grátis',
        'hero_eyebrow'     => 'Trial Grátis · Sem Cartão',
        'hero_h1_1'        => 'Assistente IA',
        'hero_h1_2'        => 'para seu site',
        'typewriter_words' => 'em 5 minutos|sem código|para todos',
        'hero_p'           => 'Uma linha de código. Todos os provedores IA suportados. Cores, persona e instruções do bot — gerenciado pelo painel.',
        'hero_cta1'        => 'Começar Grátis',
        'hero_cta2'        => 'Já tenho conta',
        'trust_1'          => 'Setup em 5 min',
        'trust_2'          => 'Sem código',
        'trust_3'          => 'Marca própria',
        'float_1'          => 'Resposta imediata',
        'float_2'          => 'Seguro & Criptografado',
        'mock_chat_bot'    => 'Olá! Como posso ajudar?',
        'mock_chat_user'   => 'Me fale sobre seu produto',
        'stat_1_num'       => '5 min',
        'stat_1_label'     => 'Tempo médio de configuração',
        'stat_2_num'       => '4',
        'stat_2_label'     => 'Provedores IA suportados',
        'stat_3_num'       => '1 linha',
        'stat_3_label'     => 'Para incorporar o widget',
        'stat_4_num'       => '99.9%',
        'stat_4_label'     => 'SLA de uptime',
        'feat_tag'         => 'Recursos Principais',
        'feat_h2'          => "Tudo que você precisa,\npronto desde o primeiro dia",
        'feat_sub'         => 'Do setup às conversas com IA contextual — tudo autogerenciado pelo painel.',
        'feat_1_h'         => 'No Ar em 5 Minutos',
        'feat_1_p'         => 'Copie uma tag de script do painel, cole no site. O widget aparece instantaneamente.',
        'feat_2_h'         => 'Multi-Provedor IA',
        'feat_2_p'         => 'OpenRouter, OpenAI, Gemini, DeepSeek. Troque de provedor a qualquer momento.',
        'feat_3_h'         => 'Totalmente Personalizável',
        'feat_3_p'         => 'Cor, nome do bot, mensagem de boas-vindas, prompt do sistema — tudo segue sua marca.',
        'feat_4_h'         => 'Memória de Conversa',
        'feat_4_p'         => 'A IA lembra do contexto em uma sessão. Visitantes não precisam se repetir.',
        'feat_5_h'         => 'Alertas no Telegram',
        'feat_5_p'         => 'Receba notificações no Telegram a cada nova mensagem — sem abrir o painel.',
        'feat_6_h'         => 'Seguro e Isolado',
        'feat_6_p'         => 'Shadow DOM protege o CSS do widget. Chaves de API criptografadas AES-256-GCM.',
        'how_tag'          => 'Como Funciona',
        'how_h2'           => 'Três etapas. Widget IA ativo.',
        'how_sub'          => 'Sem expertise técnica. Se você sabe copiar e colar, pode usar isso.',
        'step_1_h'         => 'Cadastre e Configure',
        'step_1_p'         => 'Escolha provedor IA, insira API key, escreva um prompt do sistema.',
        'step_2_h'         => 'Copie o Código',
        'step_2_p'         => 'O painel gera uma tag de script única. Um clique, copiado.',
        'step_3_h'         => 'Cole no seu Site',
        'step_3_p'         => 'Cole antes do </body> no WordPress ou qualquer landing page.',
        'prov_tag'         => 'Provedores IA',
        'prov_h2'          => 'Escolha o melhor cérebro IA',
        'prov_sub'         => 'Troque de provedor sem código. Ajuste ao seu orçamento e necessidades.',
        'prov_1'           => 'OpenRouter',
        'prov_1_tag'       => 'Recomendado · acesso a todos',
        'prov_2'           => 'OpenAI',
        'prov_2_tag'       => 'GPT-4o · GPT-4o-mini',
        'prov_3'           => 'Google Gemini',
        'prov_3_tag'       => '1.5 Flash · 1.5 Pro',
        'prov_4'           => 'DeepSeek',
        'prov_4_tag'       => 'Chat · Coder',
        'test_tag'         => 'Confiado Por',
        'test_h2'          => 'Adorado por empresas no mundo todo',
        'test_sub'         => 'Veja o que nossos usuários dizem sobre o ChatPopup.AI.',
        'test_1_body'      => '"Configurado em literalmente 4 minutos. Meu suporte caiu 60% na primeira semana."',
        'test_1_name'      => 'Alex R.',
        'test_1_role'      => 'Dono de E-commerce',
        'test_2_body'      => '"Migramos de um SaaS de chat de $200/mês para isso. Mesma qualidade, fração do custo."',
        'test_2_name'      => 'Maria S.',
        'test_2_role'      => 'Fundadora SaaS',
        'test_3_body'      => '"A notificação do Telegram é brilhante. Agora fecho leads pelo celular."',
        'test_3_name'      => 'James K.',
        'test_3_role'      => 'Marketing Digital',
        'cta_h2'           => "Dê ao seu site\num cérebro IA",
        'cta_p'            => 'Cadastre-se grátis. Sem cartão de crédito. Pronto em minutos.',
        'cta_btn'          => 'Criar Conta Grátis',
        'footer_built'     => 'Construído em PHP 8 · Hospedado na Hostinger',
        'footer_login'     => 'Entrar',
        'footer_register'  => 'Cadastro',
    ],

    /* ────────────────── JAPANESE ────────────────── */
    'ja' => [
        'html_lang'        => 'ja',
        'page_title'       => 'ChatPopup.AI — ウェブサイト向けAIチャットウィジェット',
        'page_desc'        => '5分でAIチャットウィジェットをウェブサイトに追加。マルチプロバイダー対応、カスタムブランディング、会話メモリ機能付き。',
        'dir'              => 'ltr',
        'nav_features'     => '機能',
        'nav_how'          => '使い方',
        'nav_providers'    => 'プロバイダー',
        'nav_login'        => 'ログイン',
        'nav_register'     => '無料で始める',
        'hero_eyebrow'     => '無料トライアル · クレカ不要',
        'hero_h1_1'        => 'AIアシスタントを',
        'hero_h1_2'        => 'あなたのサイトへ',
        'typewriter_words' => '5分で完成|コード不要|誰でも使える',
        'hero_p'           => '1行のコードで導入完了。全AIプロバイダー対応。色、ペルソナ、ボットの指示はダッシュボードから管理。',
        'hero_cta1'        => '無料で始める',
        'hero_cta2'        => 'すでにアカウントをお持ちの方',
        'trust_1'          => '5分でセットアップ',
        'trust_2'          => 'コード不要',
        'trust_3'          => 'ブランドカスタマイズ',
        'float_1'          => '即時返信',
        'float_2'          => '安全・暗号化',
        'mock_chat_bot'    => 'こんにちは！何かお手伝いできますか？',
        'mock_chat_user'   => '商品について教えてください',
        'stat_1_num'       => '5分',
        'stat_1_label'     => '平均セットアップ時間',
        'stat_2_num'       => '4',
        'stat_2_label'     => '対応AIプロバイダー数',
        'stat_3_num'       => '1行',
        'stat_3_label'     => 'ウィジェット埋め込み',
        'stat_4_num'       => '99.9%',
        'stat_4_label'     => '稼働率SLA',
        'feat_tag'         => '主な機能',
        'feat_h2'          => "必要なものがすべて\n初日から揃っています",
        'feat_sub'         => 'セットアップからコンテキスト対応AI会話まで、すべてダッシュボードで自己管理。',
        'feat_1_h'         => '5分で公開',
        'feat_1_p'         => 'ダッシュボードからスクリプトタグをコピーして貼り付けるだけ。ウィジェットがすぐに表示されます。',
        'feat_2_h'         => 'マルチプロバイダー対応',
        'feat_2_p'         => 'OpenRouter、OpenAI、Gemini、DeepSeek。いつでもドロップダウンから切り替え可能。',
        'feat_3_h'         => '完全カスタマイズ',
        'feat_3_p'         => 'カラー、ボット名、ウェルカムメッセージ、システムプロンプト — すべてブランドに合わせて設定。',
        'feat_4_h'         => '会話メモリ',
        'feat_4_p'         => 'AIは1セッション内のコンテキストを記憶。訪問者が繰り返す必要はありません。',
        'feat_5_h'         => 'Telegram通知',
        'feat_5_p'         => '新しいメッセージが届くたびにTelegramで通知。ダッシュボード不要。',
        'feat_6_h'         => '安全・隔離',
        'feat_6_p'         => 'Shadow DOMがウィジェットのCSSを保護。APIキーはAES-256-GCMで暗号化。',
        'how_tag'          => '使い方',
        'how_h2'           => '3ステップでAIウィジェット起動',
        'how_sub'          => '技術的な専門知識は不要。コピー&ペーストができれば使えます。',
        'step_1_h'         => '登録・設定',
        'step_1_p'         => 'AIプロバイダーを選び、APIキーを入力し、ビジネス向けシステムプロンプトを作成。',
        'step_2_h'         => '埋め込みコードをコピー',
        'step_2_p'         => 'ダッシュボードが自動で固有のスクリプトタグを生成。ワンクリックでコピー。',
        'step_3_h'         => 'サイトに貼り付け',
        'step_3_p'         => 'WordPressなど任意のページの</body>前に貼り付けるだけ。',
        'prov_tag'         => 'AIプロバイダー',
        'prov_h2'          => 'あなたに最適なAIを選ぼう',
        'prov_sub'         => 'コード不要でプロバイダーを切り替え。予算とニーズに合わせて選択。',
        'prov_1'           => 'OpenRouter',
        'prov_1_tag'       => 'おすすめ · 全モデルアクセス',
        'prov_2'           => 'OpenAI',
        'prov_2_tag'       => 'GPT-4o · GPT-4o-mini',
        'prov_3'           => 'Google Gemini',
        'prov_3_tag'       => '1.5 Flash · 1.5 Pro',
        'prov_4'           => 'DeepSeek',
        'prov_4_tag'       => 'Chat · Coder',
        'test_tag'         => '利用実績',
        'test_h2'          => '世界中のビジネスに愛用されています',
        'test_sub'         => 'ChatPopup.AIユーザーの声をご紹介します。',
        'test_1_body'      => '「文字通り4分でセットアップ完了。最初の週でサポート負荷が60%減りました。AIが本当にコンテキストを理解しています。」',
        'test_1_name'      => 'Alex R.',
        'test_1_role'      => 'EC事業オーナー',
        'test_2_body'      => '「月2万円のチャットSaaSからこれに切り替えました。同じ品質で大幅にコスト削減。」',
        'test_2_name'      => 'Maria S.',
        'test_2_role'      => 'SaaS創業者',
        'test_3_body'      => '「Telegram通知は画期的。今は訪問者がチャット中にスマホからリードをクロージングできます。」',
        'test_3_name'      => 'James K.',
        'test_3_role'      => 'デジタルマーケター',
        'cta_h2'           => "あなたのサイトに\nAIを搭載しよう",
        'cta_p'            => '無料登録。クレジットカード不要。数分で準備完了。',
        'cta_btn'          => '無料アカウント作成',
        'footer_built'     => 'PHP 8で構築 · Hostingerでホスティング',
        'footer_login'     => 'ログイン',
        'footer_register'  => '登録',
    ],

    ];

    return $all[$lang] ?? $all['en'];
}
